version: "3"

services:
  miniconda:
    container_name: miniconda-cling
    hostname: miniconda-cling
    image: miniconda-cling
    restart: unless-stopped
    ports:
      - 8666:8000
      - 8777:5000
    volumes:
      - ./notebooks:/opt/notebooks
      - ./users_home:/home